#!/usr/bin/env python
"""Simulate barcoded single-cell reads with NanoSim from the template (Methods 2.5).
"""
import gzip
import random
import sys
from collections import defaultdict
from pathlib import Path

import numpy as np

# STAIRCASE_DIR, STAIRCASE_WL and NANOSIM_POOL_FA take env overrides so misc/error_control.py can
# run an arm in its own results dir with a different NanoSim pool and whitelist.
import os
STA = Path(os.environ.get("STAIRCASE_DIR",
                          os.path.expandvars("$BENCHDROP_RESULTS/staircase")))
WL = Path(os.environ.get("STAIRCASE_WL",
                         os.path.expandvars("$BAGPIPER_DIR/test/whitelist/pip.v5.csv")))
N_CELLS = 10
DEPTH = float(sys.argv[2]) if len(sys.argv) > 2 else 25  # mean reads/gene/cell; rung 3 sweeps this
SIM_GENES = 300  # full template
DOM = 0.8       # dominant-isoform fraction
BASES = "ACGT"

# Empirical ONT profile measured from real BenchDrop K562 reads (characterize_error.py):
# sub 0.59%, ins 0.33%, del 0.78% -> 1.70% total, 65.5% of errors are indels.
P_SUB, P_INS, P_DEL = 0.0059, 0.0033, 0.0078
# rung 1 = 0.0 (clean ceiling); rung 2 = 1.0 (empirical); sweep scales this
ERROR_SCALE = float(sys.argv[1]) if len(sys.argv) > 1 else 0.0

random.seed(0)
np.random.seed(0)
# Error injection MUST draw from its own streams, otherwise changing ERROR_SCALE shifts the
# truth-assignment draws too and the clean-vs-error comparison is not on matched truth.
ERR = random.Random(12345)
ERR_NP = np.random.RandomState(12345)

# template
txseq, cur, buf = {}, None, []
for ln in open(STA / "template.fa"):
    if ln.startswith(">"):
        if cur:
            txseq[cur] = "".join(buf)
        cur, buf = ln[1:].strip(), []
    else:
        buf.append(ln.strip())
if cur:
    txseq[cur] = "".join(buf)
gene_tx = defaultdict(list)
for ln in open(STA / "template_meta.tsv"):
    if ln.startswith("transcript_id"):
        continue
    t, g, i, l = ln.rstrip("\n").split("\t")
    gene_tx[g].append(t)          # ordered by isoform_idx

# whitelist pools (columns: original_barcode_4,_3,_2,_1)
rows = [ln.rstrip("\n").split(",") for ln in open(WL)]
hdr, data = rows[0], rows[1:]
pool = {name: [r[j] for r in data] for j, name in enumerate(hdr)}


def rnd(n):
    return "".join(random.choice(BASES) for _ in range(n))


_COMP = str.maketrans("ACGT", "TGCA")


def rc(s):
    return s.translate(_COMP)[::-1]


def add_error(seq, scale):
    """Apply the empirical ONT profile to the WHOLE read (barcode + linkers + UMI + cDNA).

    Error hits the barcode region in real data too, so barcode recovery must be allowed to
    degrade here; that is what makes the rung-2 recovery rate comparable to the real 65.8%.
    Counts are drawn binomially and positions sampled, which is far faster than a per-base
    loop. i.i.d. model: it reproduces the rate and the indel:substitution split, but not
    ONT's homopolymer context bias.
    """
    if scale <= 0:
        return seq
    n = len(seq)
    if n == 0:
        return seq
    s = list(seq)
    for i in ERR.sample(range(n), min(int(ERR_NP.binomial(n, min(1.0, P_SUB * scale))), n)):
        s[i] = ERR.choice([b for b in BASES if b != s[i]])
    for i in ERR.sample(range(n), min(int(ERR_NP.binomial(n, min(1.0, P_INS * scale))), n)):
        s[i] = s[i] + ERR.choice(BASES)
    for i in ERR.sample(range(n), min(int(ERR_NP.binomial(n, min(1.0, P_DEL * scale))), n)):
        s[i] = ""
    return "".join(s)


# NanoSim error pool: SENSE-oriented errored cDNA reads per transcript, generated by REAL NanoSim
# (v3.2.3 self-trained on our K562 reads; simulator.py on template.fa). Used for the cDNA when
# ERROR_SCALE>0; the barcode/UMI segment keeps the measured per-base error. ERROR_SCALE==0 stays
# the clean ceiling rung. Any transcript NanoSim did not cover falls back to the i.i.d. path.
NANOSIM_POOL = defaultdict(list)
_POOL_FA = Path(os.environ.get("NANOSIM_POOL_FA", STA / "nanosim/sim/template_aligned_reads.fasta"))
if ERROR_SCALE > 0 and _POOL_FA.exists():
    _t, _strand, _buf = None, "F", []

    def _flush_pool():
        if _t and _buf:
            s = "".join(_buf)
            NANOSIM_POOL[_t].append(s if _strand == "F" else rc(s))   # store SENSE orientation

    for _ln in open(_POOL_FA):
        if _ln.startswith(">"):
            _flush_pool()
            _p = _ln[1:].strip().split("_")        # {tx}_{pos}_aligned_{i}_{F|R}_{head}_{mid}_{tail}
            _t, _strand, _buf = _p[0], (_p[4] if len(_p) > 4 else "F"), []
        else:
            _buf.append(_ln.strip())
    _flush_pool()
    print(f"NanoSim pool: {sum(len(v) for v in NANOSIM_POOL.values()):,} reads over "
          f"{len(NANOSIM_POOL)} transcripts", file=sys.stderr)


# assign unique combinatorial barcodes + a state to each cell
used, cells = set(), []
for c in range(N_CELLS):
    while True:
        b = (random.choice(pool["original_barcode_1"]),
             random.choice(pool["original_barcode_2"]),
             random.choice(pool["original_barcode_3"]),
             random.choice(pool["original_barcode_4"]))
        if b not in used:
            used.add(b)
            break
    cells.append((f"cell{c:04d}", *b, c % 2))

genes = list(gene_tx)[:SIM_GENES]
truth = defaultdict(int)                 # (cid, tx) -> reads
reads = []
n_fallback = 0   # reads that took the full-transcript path because the pool lacked the transcript
for cid, b1, b2, b3, b4, state in cells:
    for g in genes:
        txs = gene_tx[g]
        k = max(0, round(random.gauss(DEPTH, DEPTH * 0.3)))
        if not k:
            continue
        dom = state if state < len(txs) else 0
        for _ in range(k):
            if random.random() < DOM:
                ti = dom
            else:
                other = [x for x in range(len(txs)) if x != dom]
                ti = random.choice(other) if other else dom
            t = txs[ti]
            umi = rnd(12)
            # FORWARD architecture (bagpiper bc_fw_re, verified 100% barcode recovery):
            #   [noise] bc1 ATG bc2 GAG bc3 TCGAG bc4 UMI(12) [cDNA]
            # bagpiper writes fw-matched reads with is_polya_strand=false, i.e. it REVCOMPS
            # the cDNA on output. So emit revcomp(transcript) here; bagpiper's revcomp lands
            # it transcript-forward, which is what minimap2 --for-only requires.
            bc = rnd(4) + b1 + "ATG" + b2 + "GAG" + b3 + "TCGAG" + b4 + umi
            pool_t = NANOSIM_POOL.get(t)
            if ERROR_SCALE > 0 and pool_t:
                # NanoSim-errored cDNA (trained on our K562), emitted antisense like rc(txseq[t]);
                # the barcode/UMI segment carries the measured per-base error (barcode recovery).
                seq = add_error(bc, ERROR_SCALE) + rc(ERR.choice(pool_t))
            else:
                seq = add_error(bc + rc(txseq[t]), ERROR_SCALE)   # clean ceiling (rung 1) / fallback
                n_fallback += 1
            reads.append((f"{cid}.{g}.{t}", seq))   # '.' delimiter: cid/g/t stay parseable
            truth[(cid, t)] += 1

random.shuffle(reads)
with gzip.open(STA / "sim.rung1.fastq.gz", "wt", compresslevel=1) as fo:
    for rid, seq in reads:
        fo.write(f"@{rid}\n{seq}\n+\n{'I' * len(seq)}\n")
with open(STA / "cells.rung1.tsv", "w") as fc:
    fc.write("cid\tbc1\tbc2\tbc3\tbc4\tstate\n")
    for cid, b1, b2, b3, b4, state in cells:
        fc.write(f"{cid}\t{b1}\t{b2}\t{b3}\t{b4}\t{state}\n")
with open(STA / "truth.rung1.tsv", "w") as ft:
    ft.write("cid\ttranscript_id\ttrue_count\n")
    for (cid, t), n in truth.items():
        ft.write(f"{cid}\t{t}\t{n}\n")
print(f"cells {len(cells)}, reads {len(reads):,}, truth rows {len(truth):,}")
# The full-transcript fallback changes read length, so every run reports how many reads took it
# (0 with a full pool).
print(f"fallback reads (full transcript, no pool entry): {n_fallback:,}", file=sys.stderr)
